### ISSUE TITLE
Can't get lesbians. Help!

### ISSUE THREAD

**Issue by yonas** [noornee/reddit-dl#1]
```
$ reddit-dl -url https://www.reddit.com/r/Lesbian_gifs/comments/zvx95q/our_favourite_position_is_69
[INFO]: Parsing The URL
[INFO]: Getting the JSON body
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/noornee/reddit-dl/utility.ParseJSONBody({0xc000258500, 0x23bd, 0x2500})
        /git/reddit-dl/utility/utility.go:111 +0x7f7
main.main()
        /git/reddit-dl/main.go:42 +0x219
```

**Comment by noornee** [comment]
hii @yonas :D 

I'm sorry about that. 
Right now, reddit-dl only supports downloading gifs that are uploaded directly from reddit or shared from gfycat.com.
The video you want to download was shared from redgifs.com to reddit.com.
 it wasn't uploaded the normal way and i didn't put redgifs.com into consideration

and geez, thanks for this.
I'm going to handle the errors better for cases like this

**Comment by noornee** [comment]
hii @yonas , you can now get your lesbians ^_^
thanks to the last PR that was made by @cmd777  in #4

**Comment by yonas** [comment]
@noornee Thanks! :P

**Comment by noornee** [comment]
tee-hee :)
